[package]
name = "wasmi_backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.86"
candid = "0.10"
ic-cdk = "0.15"
wasmi = { version = "0.35.0", default-features = false }
